apiVersion: v1
kind: Service
metadata:
  name: content-creation-crew-a2a
  namespace: tenant-globex-azure
  labels:
    hexr.io/component: a2a-service
    hexr.io/agent: "content-creation-crew-a2a"
spec:
  type: ClusterIP
  selector:
    app: globex-azure-content-creation-crew-a2a
  ports:
    - name: a2a
      port: 80
      targetPort: 8090
      protocol: TCP
